### ISSUE TITLE
UWP: System.NotSupportedException when inherits from Control

### ISSUE THREAD

**Issue by kubakista** [lextm/obfuscar#110]
I am trying to obfuscate UWP library. I had issue with [NULL reference exception](https://github.com/lextm/obfuscar/issues/109), which is now solved. However, I have another issue now. It seems like that when a class inherits from `Windows.UI.Xaml.Controls.Control`, it causes following exception.

Here is sample of UWP app
https://1drv.ms/u/s!AmBs1Z14jbNIrY57qqiHPkqJD0_bTQ

    assembly: ObfuscarUwpSample, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    Loading assemblies...Extra framework folders: Done.
    hiding strings...

    Unhandled Exception: System.NotSupportedException: Version not supported: 255.255.255.255
    at Mono.Cecil.BaseAssemblyResolver.GetCorlib(AssemblyNameReference reference, ReaderParameters parameters)
    at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
    at Obfuscar.AssemblyCache.Resolve(AssemblyNameReference name, ReaderParameters parameters)
    at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
    at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
    at Mono.Cecil.TypeReference.Resolve()
    at Obfuscar.Helpers.TypeDefinitionExtensions.IsFormOrUserControl(TypeDefinition type)
    at Obfuscar.Helpers.TypeDefinitionExtensions.IsResourcesType(TypeDefinition type)
    at Obfuscar.AssemblyInfo.ShouldSkipStringHiding(MethodKey method, InheritMap map, Boolean projectHideStrings)
    at Obfuscar.Obfuscator.StringSqueeze.ProcessStrings(MethodDefinition method, AssemblyInfo info, Project project)
    at Obfuscar.Obfuscator.HideStrings()
    at Obfuscar.Obfuscator.RunRules()
    at Obfuscar.Program.Main(String[] args)`

**Comment by lextm** [comment]
I will take a look later and write back, but the call stack indicates it can be an issue of Mono Cecil.

**Comment by lextm** [comment]
Summary so far. It turns out to be Mono Cecil issue where it fails to accept a very strange but valid version number.

I commit a specific patch to master branch, which you can build and test out. On my machine it seems to address the issue.
