### ISSUE TITLE
System.ArgumentOutOfRangeException in AssemblyCache

### ISSUE THREAD

**Issue by i3jjnc68emm** [lextm/obfuscar#133]
Trying to obfuscate an assembly and receiving a System.ArgumentOutOfRangeException exception in AssemblyCache.cs line 114

Stacktrace:
```
at System.IO.BinaryReader.ReadBytes(Int32 count)
   at Mono.Cecil.PE.ImageReader.ReadDebugHeader()
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Mono.Cecil.BaseAssemblyResolver.SearchDirectory(AssemblyNameReference name, IEnumerable`1 directories, ReaderParameters parameters)
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Obfuscar.AssemblyCache.Resolve(AssemblyNameReference name, ReaderParameters parameters) in C:\\Benjamins\\Benjamin\\Desktop\\obfuscar-2.2.11\\Obfuscar\\AssemblyCache.cs:Line 114.
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Obfuscar.AssemblyCache.GetTypeDefinition(TypeReference type) in C:\\Benjamins\\Benjamin\\Desktop\\obfuscar-2.2.11\\Obfuscar\\AssemblyCache.cs:Line 66.
   at Obfuscar.InheritMap.GetVirtualMethods(AssemblyCache cache, HashSet`1 methods, TypeDefinition type) in C:\\Benjamins\\Benjamin\\Desktop\\obfuscar-2.2.11\\Obfuscar\\InheritMap.cs:Line 192.
   at Obfuscar.InheritMap.GetVirtualMethods(AssemblyCache cache, TypeDefinition type) in C:\\Benjamins\\Benjamin\\Desktop\\obfuscar-2.2.11\\Obfuscar\\InheritMap.cs:Line 208.
   at Obfuscar.InheritMap..ctor(Project project) in C:\\Benjamins\\Benjamin\\Desktop\\obfuscar-2.2.11\\Obfuscar\\InheritMap.cs:Line 90.
   at Obfuscar.Project.LoadAssemblies() in C:\\Benjamins\\Benjamin\\Desktop\\obfuscar-2.2.11\\Obfuscar\\Project.cs:Line 381.
   at Obfuscar.Obfuscator.LoadFromReader(XDocument reader, String projectFileDirectory) in C:\\Benjamins\\Benjamin\\Desktop\\obfuscar-2.2.11\\Obfuscar\\Obfuscator.cs:Line 176.
   at Obfuscar.Obfuscator..ctor(String projfile) in C:\\Benjamins\\Benjamin\\Desktop\\obfuscar-2.2.11\\Obfuscar\\Obfuscator.cs:Line 89.
   at Obfuscar.Program.Main(String[] args) in C:\\Benjamins\\Benjamin\\Desktop\\obfuscar-2.2.11\\Console\\Program.cs:Line 112."
```

**Comment by lextm** [comment]
Mono Cecil does not work for all assemblies. Such issues can only be addressed by Mono Cecil developers.

**Comment by t1t7mgn6k1n** [comment]
The bug occurs if a third party dll has been (partly) obfuscated. However other obfuscators can handle it and they are using mono cecil as well for example Eazfuscator. Also DnSpy has no issues dealing with this.

Only Obfuscar fails.

**Comment by lextm** [comment]
Different tools use different Mono Cecil assemblies (versions, forks). 

Obfuscar uses the standard one from NuGet, so I have no plan to switch. 

DnSpy uses dnlib, so it has little to do with Mono Cecil.
