### ISSUE TITLE
System.ArgumentException: Item has already been added. Key in dictionary: Upon launching

### ISSUE THREAD

**Issue by AmitBhatnagar24** [lextm/obfuscar#137]
I have run my exe and associated assemblies thru obfuscar by installing the nuget package an creating a build post event, just like the BasicExample.

When I then try to launch my exe, it immediately crashes.. when launched via the command line, I see this:

```
Unhandled Exception: System.ArgumentException: Item has already been added. Key in dictionary: 'A'  Key being added: 'a'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Configuration.SettingsPropertyCollection.Add(SettingsProperty property)
   at System.Configuration.ApplicationSettingsBase.EnsureInitialized()
   at System.Configuration.ApplicationSettingsBase.get_Properties()
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at mycorp.App.product.App.A()
   at mycorp.App.product.App..ctor()
   at mycorp.App.product.App.Main()
```

This doesn't seem to be mentioned in the FAQ (http://docs.obfuscar.com/en/latest/getting-started/faq.html).

I'm wondering if anyone else had this issue and knows how to fix it?

**Comment by lextm** [comment]
Not all code can be obfuscated, so in your case you might have to exclude something, http://docs.obfuscar.com/en/latest/getting-started/configuration.html#exclusion-rules-by-configuration

**Comment by AmitBhatnagar24** [comment]
Thanks for the response @lextm 

So I removed the lines of code that were obtaining settings (as my original post showed), and then retried the obfuscar. I now get this exception:

```
Unhandled Exception: System.Windows.Markup.XamlParseException: The method or operation is not implemented. ---> System.NotImplementedException: The method or operation is not implemented.
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlType(BamlType bamlType, Int16 typeId)
   at System.Windows.Baml2006.Baml2006SchemaContext.GetXamlType(Int16 typeId)
   at System.Windows.Baml2006.Baml2006Reader.Process_ElementStart()
   at System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
   at System.Windows.Baml2006.Baml2006Reader.Process_BamlRecords()
   at System.Windows.Baml2006.Baml2006Reader.Read()
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at A5Digital.App.navisCompiler.App.InitializeComponent()
   at A5Digital.App.navisCompiler.App.Main()
```
Is there an easy way to identify exactly what can't be obfuscated so I can exclude them like you suggest?

**Comment by AmitBhatnagar24** [comment]
So I am still way confused. As per your suggestion, I have excluded my entire namespace where it may be picking up any XAML converters, yet still launching the app immediately crashes... any way to pinpoint what is the problem?

**Comment by lextm** [comment]
If the crash shows a similar call stack to what you shared earlier, then to know why, you just need to use a debugger (personally I will use WinDbg). Launch the obfuscated program with the debugger attached, let it crash, and then walk on the stack to check what exactly the XAML related classes are doing.

Generally speaking, Obfuscar was not tested fully with WPF apps (as most of it was written before WPF was popular), so I don't recommend using it on WPF specific assemblies.

**Comment by protegesolutions** [comment]
I have the same issue. In my case I have 5 assemblies in the project and I can only obfuscate the "top" one (ie, the main application of which the other fours are sub-assemblies).

It's extremely frustrating as once the assembly is obfuscated, no debug symbols are loaded so you can step into the errant assembly.

Obfuscar would be a lot better if the documentation was more thorough and there were better guidelines on how to debug this kind of thing. Just say that it we created before WPF so don't use it with WPF is a little disappointing to hear.

**Comment by Rainb0wCodes** [comment]
BTW for me this case of error was caused by x:Class pointing to MainWindow

**Comment by lextm** [comment]
Duplicate to #551
