### ISSUE TITLE
Crashes when compiling 64-bit and specifying a strongname

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lextm/obfuscar#52]
```
obfuscar 2.0_rc7 on Window 8.1 64-bit, compiling a 64-bit Outlook Addin
I can get x86 to compile and obfuscate without problem, but not x64

Log
=========================
  Trying to resolve dependency: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  Trying to resolve dependency: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  Trying to resolve dependency: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  Done.
  Renaming:  fields...parameters...properties...events...methods...types...hiding strings...
  Done.
  
  Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
     at Mono.Security.StrongName.Sign(String fileName)
     at Obfuscar.Obfuscator.SaveAssemblies()
     at Obfuscar.Obfuscator.RunRules()
     at Obfuscar.Program.Main(String[] args)
  Saving assemblies...
C:\Program Files 
(x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(4429,5): error 
MSB3073: The command ""C:\Program Files (x86)\Obfuscar\Obfuscar.Console.exe" 
"..\..\..\Release Files\obfuscar.xml"" exited with code -1073741819.




```

Original issue reported on code.google.com by `glenbell...@gmail.com` on 24 Feb 2014 at 10:19

**Comment by lextm** [comment]
Cannot reproduce. Further information is needed.
