### ISSUE TITLE
Obfuscar hangs or throws exception

### ISSUE THREAD

**Issue by kanekotic** [lextm/obfuscar#68]
I have the next behavior with obfuscar:
-  with all my dlls and exe obfuscar hangs or enters an infinite loop.
- when I have removed one specific dll and add the exe obfuscar works 
- Obfuscar is getting the next exception when obfuscating my project (in the case i exclude the .exe only dlls)

```
Loading assemblies...Extra framework folders: Done.
hiding strings...
Renaming:  fields...parameters...properties...events...methods...types...Done.
Saving assemblies...
Unhandled Exception: Mono.Cecil.ResolutionException: Failed to resolve A.m
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)
   at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypeDefs()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.ModuleWriter.<BuildMetadata>b__0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Obfuscar.Obfuscator.SaveAssemblies()
   at Obfuscar.Obfuscator.RunRules()
   at Obfuscar.Program.Main(String[] args)
```

as extra information my project in .net 4.6, could this be an issue?.

**Comment by dedale** [comment]
Look at #70 : I fixed a bug where Obfuscar was hanging. I also added some log to understand some "Failed to resolve" errors. In my cases, this was usually an enum.

**Comment by lextm** [comment]
Temp close unless more info is provided.
