### ISSUE TITLE
Exception for assemblies created by NETCore SDK 'Sequence contains no matching elements'

### ISSUE THREAD

**Issue by VitaliyMF** [lextm/obfuscar#85]
I've tried to obfuscate assembly generated with 'dotnet build' (NETCore SDK) and got the following exception:

```
Unhandled Exception: System.InvalidOperationException: Sequence contains no matc
hing element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Obfuscar.Helpers.AssemblyDefinitionExtensions.GetPortableProfileDirectory(AssemblyDefinition assembly)
   at Obfuscar.AssemblyCache.RegisterAssembly(AssemblyDefinition assembly)
   at Obfuscar.AssemblyInfo.LoadAssembly(String filename)
   at Obfuscar.AssemblyInfo.FromXml(Project project, XmlReader reader, Variables vars)
   at Obfuscar.Project.FromXml(XmlReader reader, String projectFileDirectory)
   at Obfuscar.Obfuscator.LoadFromReader(XmlReader reader, String projectFileDirectory)
   at Obfuscar.Obfuscator..ctor(String projfile)
   at Obfuscar.Program.Main(String[] args)
```
This exception is thrown both for assembly that targets netstandard1.5 and net40. Note that this exception is not thrown if DLL is compiled by visual studio (portable library that targets netstandard).

**Comment by lextm** [comment]
Thanks. I left some comments in the PR. Please update it so that I can accept it.
